name: 'kafka'
version: 0.1.0
description: Kafka client library for Dartlang
homepage: https://github.com/dart-drivers/kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: ^2.4.1
  quiver: ^2.1.3
  logging: ^0.11.4
  pool: ^1.4.0

dev_dependencies:
  test: ^1.8.0
  mockito: ^4.1.1
  dart_coveralls: ^0.6.0+4
  string_scanner: ^1.0.5
  source_span: ^1.7.0
